
/*
Autogenerated file from Nfantom.RPC
*/

using System;
using System.Text;
using Nfantom.JsonRpc.Client;
using Newtonsoft.Json;
using System.Collections;
using Nfantom.Hex.HexTypes;
using Nfantom.RPC.Eth.DTOs;

namespace Nfantom.Unity
{

    public class Web3ClientVersionUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Web3.Web3ClientVersion _web3ClientVersion;

        public Web3ClientVersionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _web3ClientVersion = new RPC.Web3.Web3ClientVersion(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _web3ClientVersion.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class Web3Sha3UnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Web3.Web3Sha3 _web3Sha3;

        public Web3Sha3UnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _web3Sha3 = new RPC.Web3.Web3Sha3(null);
        }

        public IEnumerator SendRequest(HexUTF8String valueToConvert)
        {
            var request = _web3Sha3.BuildRequest(valueToConvert);
            yield return SendRequest(request);
        }
    }


    public class ShhNewKeyPairUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Shh.KeyPair.ShhNewKeyPair _shhNewKeyPair;

        public ShhNewKeyPairUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _shhNewKeyPair = new RPC.Shh.KeyPair.ShhNewKeyPair(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _shhNewKeyPair.BuildRequest();
            yield return SendRequest(request);
        }
    }

    public class ShhAddPrivateKeyUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Shh.KeyPair.ShhAddPrivateKey _addPrivateKey;

        public ShhAddPrivateKeyUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _addPrivateKey = new RPC.Shh.KeyPair.ShhAddPrivateKey(null);
        }

        public IEnumerator SendRequest(string privateKey)
        {
            var request = _addPrivateKey.BuildRequest(privateKey);
            yield return SendRequest(request);
        }
    }

    public class ShhVersionUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Shh.ShhVersion _shhVersion;

        public ShhVersionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _shhVersion = new RPC.Shh.ShhVersion(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _shhVersion.BuildRequest();
            yield return SendRequest(request);
        }
    }

    public class PersonalListAccountsUnityRequest : UnityRpcClient<string[]>
    {
        private readonly RPC.Personal.PersonalListAccounts _personalListAccounts;

        public PersonalListAccountsUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _personalListAccounts = new RPC.Personal.PersonalListAccounts(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _personalListAccounts.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class PersonalLockAccountUnityRequest : UnityRpcClient<bool>
    {
        private readonly RPC.Personal.PersonalLockAccount _personalLockAccount;

        public PersonalLockAccountUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _personalLockAccount = new RPC.Personal.PersonalLockAccount(null);
        }

        public IEnumerator SendRequest(string account)
        {
            var request = _personalLockAccount.BuildRequest(account);
            yield return SendRequest(request);
        }
    }


    public class PersonalNewAccountUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Personal.PersonalNewAccount _personalNewAccount;

        public PersonalNewAccountUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _personalNewAccount = new RPC.Personal.PersonalNewAccount(null);
        }

        public IEnumerator SendRequest(string passPhrase)
        {
            var request = _personalNewAccount.BuildRequest(passPhrase);
            yield return SendRequest(request);
        }
    }


    public class PersonalSignAndSendTransactionUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Personal.PersonalSignAndSendTransaction _personalSignAndSendTransaction;

        public PersonalSignAndSendTransactionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _personalSignAndSendTransaction = new RPC.Personal.PersonalSignAndSendTransaction(null);
        }

        public IEnumerator SendRequest(TransactionInput txn, string password)
        {
            var request = _personalSignAndSendTransaction.BuildRequest(txn, password);
            yield return SendRequest(request);
        }
    }


    public class PersonalUnlockAccountUnityRequest : UnityRpcClient<bool>
    {
        private readonly RPC.Personal.PersonalUnlockAccount _personalUnlockAccount;

        public PersonalUnlockAccountUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _personalUnlockAccount = new RPC.Personal.PersonalUnlockAccount(null);
        }

        public IEnumerator SendRequest(string address, string passPhrase, int durationInSeconds)
        {
            var request = _personalUnlockAccount.BuildRequest(address, passPhrase, durationInSeconds);
            yield return SendRequest(request);
        }
    }


    public class NetListeningUnityRequest : UnityRpcClient<bool>
    {
        private readonly RPC.Net.NetListening _netListening;

        public NetListeningUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _netListening = new RPC.Net.NetListening(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _netListening.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class NetPeerCountUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Net.NetPeerCount _netPeerCount;

        public NetPeerCountUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _netPeerCount = new RPC.Net.NetPeerCount(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _netPeerCount.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class NetVersionUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Net.NetVersion _netVersion;

        public NetVersionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _netVersion = new RPC.Net.NetVersion(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _netVersion.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthAccountsUnityRequest : UnityRpcClient<string[]>
    {
        private readonly RPC.Eth.EthAccounts _ethAccounts;

        public EthAccountsUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethAccounts = new RPC.Eth.EthAccounts(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethAccounts.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthCoinBaseUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Eth.EthCoinBase _ethCoinBase;

        public EthCoinBaseUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethCoinBase = new RPC.Eth.EthCoinBase(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethCoinBase.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthGasPriceUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.EthGasPrice _ethGasPrice;

        public EthGasPriceUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGasPrice = new RPC.Eth.EthGasPrice(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethGasPrice.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthGetBalanceUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.EthGetBalance _ethGetBalance;

        public EthGetBalanceUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetBalance = new RPC.Eth.EthGetBalance(null);
        }

        public IEnumerator SendRequest(string address, BlockParameter block)
        {
            var request = _ethGetBalance.BuildRequest(address, block);
            yield return SendRequest(request);
        }
    }


    public class EthGetCodeUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Eth.EthGetCode _ethGetCode;

        public EthGetCodeUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetCode = new RPC.Eth.EthGetCode(null);
        }

        public IEnumerator SendRequest(string address, BlockParameter block)
        {
            var request = _ethGetCode.BuildRequest(address, block);
            yield return SendRequest(request);
        }
    }


    public class EthGetStorageAtUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Eth.EthGetStorageAt _ethGetStorageAt;

        public EthGetStorageAtUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetStorageAt = new RPC.Eth.EthGetStorageAt(null);
        }

        public IEnumerator SendRequest(string address, HexBigInteger position, BlockParameter block)
        {
            var request = _ethGetStorageAt.BuildRequest(address, position, block);
            yield return SendRequest(request);
        }
    }


    public class EthProtocolVersionUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Eth.EthProtocolVersion _ethProtocolVersion;

        public EthProtocolVersionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethProtocolVersion = new RPC.Eth.EthProtocolVersion(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethProtocolVersion.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthSignUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Eth.EthSign _ethSign;

        public EthSignUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethSign = new RPC.Eth.EthSign(null);
        }

        public IEnumerator SendRequest(string address, string data)
        {
            var request = _ethSign.BuildRequest(address, data);
            yield return SendRequest(request);
        }
    }


    public class EthSyncingUnityRequest : UnityRpcClient<object>
    {
        private readonly RPC.Eth.EthSyncing _ethSyncing;

        public EthSyncingUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethSyncing = new RPC.Eth.EthSyncing(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethSyncing.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthGetUncleByBlockHashAndIndexUnityRequest : UnityRpcClient<BlockWithTransactionHashes>
    {
        private readonly RPC.Eth.Uncles.EthGetUncleByBlockHashAndIndex _ethGetUncleByBlockHashAndIndex;

        public EthGetUncleByBlockHashAndIndexUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetUncleByBlockHashAndIndex = new RPC.Eth.Uncles.EthGetUncleByBlockHashAndIndex(null);
        }

        public IEnumerator SendRequest(string blockHash, HexBigInteger uncleIndex)
        {
            var request = _ethGetUncleByBlockHashAndIndex.BuildRequest(blockHash, uncleIndex);
            yield return SendRequest(request);
        }
    }


    public class EthGetUncleByBlockNumberAndIndexUnityRequest : UnityRpcClient<BlockWithTransactionHashes>
    {
        private readonly RPC.Eth.Uncles.EthGetUncleByBlockNumberAndIndex _ethGetUncleByBlockNumberAndIndex;

        public EthGetUncleByBlockNumberAndIndexUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetUncleByBlockNumberAndIndex = new RPC.Eth.Uncles.EthGetUncleByBlockNumberAndIndex(null);
        }

        public IEnumerator SendRequest(BlockParameter blockParameter, HexBigInteger uncleIndex)
        {
            var request = _ethGetUncleByBlockNumberAndIndex.BuildRequest(blockParameter, uncleIndex);
            yield return SendRequest(request);
        }
    }


    public class EthGetUncleCountByBlockHashUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Uncles.EthGetUncleCountByBlockHash _ethGetUncleCountByBlockHash;

        public EthGetUncleCountByBlockHashUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetUncleCountByBlockHash = new RPC.Eth.Uncles.EthGetUncleCountByBlockHash(null);
        }

        public IEnumerator SendRequest(string hash)
        {
            var request = _ethGetUncleCountByBlockHash.BuildRequest(hash);
            yield return SendRequest(request);
        }
    }


    public class EthGetUncleCountByBlockNumberUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Uncles.EthGetUncleCountByBlockNumber _ethGetUncleCountByBlockNumber;

        public EthGetUncleCountByBlockNumberUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetUncleCountByBlockNumber = new RPC.Eth.Uncles.EthGetUncleCountByBlockNumber(null);
        }

        public IEnumerator SendRequest(HexBigInteger blockNumber)
        {
            var request = _ethGetUncleCountByBlockNumber.BuildRequest(blockNumber);
            yield return SendRequest(request);
        }
    }


    public class EthCallUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Eth.Transactions.EthCall _ethCall;

        public EthCallUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethCall = new RPC.Eth.Transactions.EthCall(null);
        }

        public IEnumerator SendRequest(CallInput callInput, BlockParameter block)
        {
            var request = _ethCall.BuildRequest(callInput, block);
            yield return SendRequest(request);
        }
    }


    public class EthEstimateGasUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Transactions.EthEstimateGas _ethEstimateGas;

        public EthEstimateGasUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethEstimateGas = new RPC.Eth.Transactions.EthEstimateGas(null);
        }

        public IEnumerator SendRequest(CallInput callInput)
        {
            var request = _ethEstimateGas.BuildRequest(callInput);
            yield return SendRequest(request);
        }
    }


    public class EthGetTransactionByBlockHashAndIndexUnityRequest : UnityRpcClient<Transaction>
    {
        private readonly RPC.Eth.Transactions.EthGetTransactionByBlockHashAndIndex _ethGetTransactionByBlockHashAndIndex;

        public EthGetTransactionByBlockHashAndIndexUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetTransactionByBlockHashAndIndex = new RPC.Eth.Transactions.EthGetTransactionByBlockHashAndIndex(null);
        }

        public IEnumerator SendRequest(string blockHash, HexBigInteger transactionIndex)
        {
            var request = _ethGetTransactionByBlockHashAndIndex.BuildRequest(blockHash, transactionIndex);
            yield return SendRequest(request);
        }
    }


    public class EthGetTransactionByBlockNumberAndIndexUnityRequest : UnityRpcClient<Transaction>
    {
        private readonly RPC.Eth.Transactions.EthGetTransactionByBlockNumberAndIndex _ethGetTransactionByBlockNumberAndIndex;

        public EthGetTransactionByBlockNumberAndIndexUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetTransactionByBlockNumberAndIndex = new RPC.Eth.Transactions.EthGetTransactionByBlockNumberAndIndex(null);
        }

        public IEnumerator SendRequest(HexBigInteger blockNumber, HexBigInteger transactionIndex)
        {
            var request = _ethGetTransactionByBlockNumberAndIndex.BuildRequest(blockNumber, transactionIndex);
            yield return SendRequest(request);
        }
    }


    public class EthGetTransactionByHashUnityRequest : UnityRpcClient<Transaction>
    {
        private readonly RPC.Eth.Transactions.EthGetTransactionByHash _ethGetTransactionByHash;

        public EthGetTransactionByHashUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetTransactionByHash = new RPC.Eth.Transactions.EthGetTransactionByHash(null);
        }

        public IEnumerator SendRequest(string hashTransaction)
        {
            var request = _ethGetTransactionByHash.BuildRequest(hashTransaction);
            yield return SendRequest(request);
        }
    }


    public class EthGetTransactionCountUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Transactions.EthGetTransactionCount _ethGetTransactionCount;

        public EthGetTransactionCountUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetTransactionCount = new RPC.Eth.Transactions.EthGetTransactionCount(null);
        }

        public IEnumerator SendRequest(string address, BlockParameter block)
        {
            var request = _ethGetTransactionCount.BuildRequest(address, block);
            yield return SendRequest(request);
        }
    }


    public class EthGetTransactionReceiptUnityRequest : UnityRpcClient<TransactionReceipt>
    {
        private readonly RPC.Eth.Transactions.EthGetTransactionReceipt _ethGetTransactionReceipt;

        public EthGetTransactionReceiptUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetTransactionReceipt = new RPC.Eth.Transactions.EthGetTransactionReceipt(null);
        }

        public IEnumerator SendRequest(string transactionHash)
        {
            var request = _ethGetTransactionReceipt.BuildRequest(transactionHash);
            yield return SendRequest(request);
        }
    }


    public class EthSendRawTransactionUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Eth.Transactions.EthSendRawTransaction _ethSendRawTransaction;

        public EthSendRawTransactionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethSendRawTransaction = new RPC.Eth.Transactions.EthSendRawTransaction(null);
        }

        public IEnumerator SendRequest(string signedTransactionData)
        {
            var request = _ethSendRawTransaction.BuildRequest(signedTransactionData);
            yield return SendRequest(request);
        }
    }


    public class EthSendTransactionUnityRequest : UnityRpcClient<string>
    {
        private readonly RPC.Eth.Transactions.EthSendTransaction _ethSendTransaction;

        public EthSendTransactionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethSendTransaction = new RPC.Eth.Transactions.EthSendTransaction(null);
        }

        public IEnumerator SendRequest(TransactionInput input)
        {
            var request = _ethSendTransaction.BuildRequest(input);
            yield return SendRequest(request);
        }
    }


    public class EthGetWorkUnityRequest : UnityRpcClient<string[]>
    {
        private readonly RPC.Eth.Mining.EthGetWork _ethGetWork;

        public EthGetWorkUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetWork = new RPC.Eth.Mining.EthGetWork(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethGetWork.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthHashrateUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Mining.EthHashrate _ethHashrate;

        public EthHashrateUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethHashrate = new RPC.Eth.Mining.EthHashrate(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethHashrate.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthMiningUnityRequest : UnityRpcClient<bool>
    {
        private readonly RPC.Eth.Mining.EthMining _ethMining;

        public EthMiningUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethMining = new RPC.Eth.Mining.EthMining(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethMining.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthSubmitHashrateUnityRequest : UnityRpcClient<bool>
    {
        private readonly RPC.Eth.Mining.EthSubmitHashrate _ethSubmitHashrate;

        public EthSubmitHashrateUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethSubmitHashrate = new RPC.Eth.Mining.EthSubmitHashrate(null);
        }

        public IEnumerator SendRequest(string hashRate, string clientId)
        {
            var request = _ethSubmitHashrate.BuildRequest(hashRate, clientId);
            yield return SendRequest(request);
        }
    }


    public class EthSubmitWorkUnityRequest : UnityRpcClient<bool>
    {
        private readonly RPC.Eth.Mining.EthSubmitWork _ethSubmitWork;

        public EthSubmitWorkUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethSubmitWork = new RPC.Eth.Mining.EthSubmitWork(null);
        }

        public IEnumerator SendRequest(string nonce, string header, string mix)
        {
            var request = _ethSubmitWork.BuildRequest(nonce, header, mix);
            yield return SendRequest(request);
        }
    }


    public class EthGetFilterChangesForEthNewFilterUnityRequest : UnityRpcClient<FilterLog[]>
    {
        private readonly RPC.Eth.Filters.EthGetFilterChangesForEthNewFilter _ethGetFilterChangesForEthNewFilter;

        public EthGetFilterChangesForEthNewFilterUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetFilterChangesForEthNewFilter = new RPC.Eth.Filters.EthGetFilterChangesForEthNewFilter(null);
        }

        public IEnumerator SendRequest(HexBigInteger filterId)
        {
            var request = _ethGetFilterChangesForEthNewFilter.BuildRequest(filterId);
            yield return SendRequest(request);
        }
    }


    public class EthGetFilterChangesForBlockOrTransactionUnityRequest : UnityRpcClient<string[]>
    {
        private readonly RPC.Eth.Filters.EthGetFilterChangesForBlockOrTransaction _ethGetFilterChangesForBlockOrTransaction;

        public EthGetFilterChangesForBlockOrTransactionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetFilterChangesForBlockOrTransaction = new RPC.Eth.Filters.EthGetFilterChangesForBlockOrTransaction(null);
        }

        public IEnumerator SendRequest(HexBigInteger filterId)
        {
            var request = _ethGetFilterChangesForBlockOrTransaction.BuildRequest(filterId);
            yield return SendRequest(request);
        }
    }


    public class EthGetFilterLogsForBlockOrTransactionUnityRequest : UnityRpcClient<string[]>
    {
        private readonly RPC.Eth.Filters.EthGetFilterLogsForBlockOrTransaction _ethGetFilterLogsForBlockOrTransaction;

        public EthGetFilterLogsForBlockOrTransactionUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetFilterLogsForBlockOrTransaction = new RPC.Eth.Filters.EthGetFilterLogsForBlockOrTransaction(null);
        }

        public IEnumerator SendRequest(HexBigInteger filterId)
        {
            var request = _ethGetFilterLogsForBlockOrTransaction.BuildRequest(filterId);
            yield return SendRequest(request);
        }
    }


    public class EthGetFilterLogsForEthNewFilterUnityRequest : UnityRpcClient<FilterLog[]>
    {
        private readonly RPC.Eth.Filters.EthGetFilterLogsForEthNewFilter _ethGetFilterLogsForEthNewFilter;

        public EthGetFilterLogsForEthNewFilterUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetFilterLogsForEthNewFilter = new RPC.Eth.Filters.EthGetFilterLogsForEthNewFilter(null);
        }

        public IEnumerator SendRequest(HexBigInteger filterId)
        {
            var request = _ethGetFilterLogsForEthNewFilter.BuildRequest(filterId);
            yield return SendRequest(request);
        }
    }


    public class EthGetLogsUnityRequest : UnityRpcClient<FilterLog[]>
    {
        private readonly RPC.Eth.Filters.EthGetLogs _ethGetLogs;

        public EthGetLogsUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetLogs = new RPC.Eth.Filters.EthGetLogs(null);
        }

        public IEnumerator SendRequest(NewFilterInput newFilter)
        {
            var request = _ethGetLogs.BuildRequest(newFilter);
            yield return SendRequest(request);
        }
    }


    public class EthNewBlockFilterUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Filters.EthNewBlockFilter _ethNewBlockFilter;

        public EthNewBlockFilterUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethNewBlockFilter = new RPC.Eth.Filters.EthNewBlockFilter(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethNewBlockFilter.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthNewFilterUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Filters.EthNewFilter _ethNewFilter;

        public EthNewFilterUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethNewFilter = new RPC.Eth.Filters.EthNewFilter(null);
        }

        public IEnumerator SendRequest(NewFilterInput newFilterInput)
        {
            var request = _ethNewFilter.BuildRequest(newFilterInput);
            yield return SendRequest(request);
        }
    }


    public class EthNewPendingTransactionFilterUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Filters.EthNewPendingTransactionFilter _ethNewPendingTransactionFilter;

        public EthNewPendingTransactionFilterUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethNewPendingTransactionFilter = new RPC.Eth.Filters.EthNewPendingTransactionFilter(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethNewPendingTransactionFilter.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthUninstallFilterUnityRequest : UnityRpcClient<bool>
    {
        private readonly RPC.Eth.Filters.EthUninstallFilter _ethUninstallFilter;

        public EthUninstallFilterUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethUninstallFilter = new RPC.Eth.Filters.EthUninstallFilter(null);
        }

        public IEnumerator SendRequest(HexBigInteger filterId)
        {
            var request = _ethUninstallFilter.BuildRequest(filterId);
            yield return SendRequest(request);
        }
    }


    public class EthCompileLLLUnityRequest : UnityRpcClient<Newtonsoft.Json.Linq.JObject>
    {
        private readonly RPC.Eth.Compilation.EthCompileLLL _ethCompileLLL;

        public EthCompileLLLUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethCompileLLL = new RPC.Eth.Compilation.EthCompileLLL(null);
        }

        public IEnumerator SendRequest(string lllcode)
        {
            var request = _ethCompileLLL.BuildRequest(lllcode);
            yield return SendRequest(request);
        }
    }


    public class EthCompileSerpentUnityRequest : UnityRpcClient<Newtonsoft.Json.Linq.JObject>
    {
        private readonly RPC.Eth.Compilation.EthCompileSerpent _ethCompileSerpent;

        public EthCompileSerpentUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethCompileSerpent = new RPC.Eth.Compilation.EthCompileSerpent(null);
        }

        public IEnumerator SendRequest(string serpentCode)
        {
            var request = _ethCompileSerpent.BuildRequest(serpentCode);
            yield return SendRequest(request);
        }
    }


    public class EthCompileSolidityUnityRequest : UnityRpcClient<Newtonsoft.Json.Linq.JToken>
    {
        private readonly RPC.Eth.Compilation.EthCompileSolidity _ethCompileSolidity;

        public EthCompileSolidityUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethCompileSolidity = new RPC.Eth.Compilation.EthCompileSolidity(null);
        }

        public IEnumerator SendRequest(string contractCode)
        {
            var request = _ethCompileSolidity.BuildRequest(contractCode);
            yield return SendRequest(request);
        }
    }


    public class EthGetCompilersUnityRequest : UnityRpcClient<string[]>
    {
        private readonly RPC.Eth.Compilation.EthGetCompilers _ethGetCompilers;

        public EthGetCompilersUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetCompilers = new RPC.Eth.Compilation.EthGetCompilers(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethGetCompilers.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthBlockNumberUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Blocks.EthBlockNumber _ethBlockNumber;

        public EthBlockNumberUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethBlockNumber = new RPC.Eth.Blocks.EthBlockNumber(null);
        }

        public IEnumerator SendRequest()
        {
            var request = _ethBlockNumber.BuildRequest();
            yield return SendRequest(request);
        }
    }


    public class EthGetBlockWithTransactionsByHashUnityRequest : UnityRpcClient<BlockWithTransactions>
    {
        private readonly RPC.Eth.Blocks.EthGetBlockWithTransactionsByHash _ethGetBlockWithTransactionsByHash;

        public EthGetBlockWithTransactionsByHashUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetBlockWithTransactionsByHash = new RPC.Eth.Blocks.EthGetBlockWithTransactionsByHash(null);
        }

        public IEnumerator SendRequest(string blockHash)
        {
            var request = _ethGetBlockWithTransactionsByHash.BuildRequest(blockHash);
            yield return SendRequest(request);
        }
    }


    public class EthGetBlockWithTransactionsHashesByHashUnityRequest : UnityRpcClient<BlockWithTransactionHashes>
    {
        private readonly RPC.Eth.Blocks.EthGetBlockWithTransactionsHashesByHash _ethGetBlockWithTransactionsHashesByHash;

        public EthGetBlockWithTransactionsHashesByHashUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetBlockWithTransactionsHashesByHash = new RPC.Eth.Blocks.EthGetBlockWithTransactionsHashesByHash(null);
        }

        public IEnumerator SendRequest(string blockHash)
        {
            var request = _ethGetBlockWithTransactionsHashesByHash.BuildRequest(blockHash);
            yield return SendRequest(request);
        }
    }


    public class EthGetBlockWithTransactionsByNumberUnityRequest : UnityRpcClient<BlockWithTransactions>
    {
        private readonly RPC.Eth.Blocks.EthGetBlockWithTransactionsByNumber _ethGetBlockWithTransactionsByNumber;

        public EthGetBlockWithTransactionsByNumberUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetBlockWithTransactionsByNumber = new RPC.Eth.Blocks.EthGetBlockWithTransactionsByNumber(null);
        }

        public IEnumerator SendRequest(HexBigInteger number)
        {
            var request = _ethGetBlockWithTransactionsByNumber.BuildRequest(number);
            yield return SendRequest(request);
        }
    }


    public class EthGetBlockTransactionCountByHashUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Blocks.EthGetBlockTransactionCountByHash _ethGetBlockTransactionCountByHash;

        public EthGetBlockTransactionCountByHashUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetBlockTransactionCountByHash = new RPC.Eth.Blocks.EthGetBlockTransactionCountByHash(null);
        }

        public IEnumerator SendRequest(string hash)
        {
            var request = _ethGetBlockTransactionCountByHash.BuildRequest(hash);
            yield return SendRequest(request);
        }
    }


    public class EthGetBlockTransactionCountByNumberUnityRequest : UnityRpcClient<HexBigInteger>
    {
        private readonly RPC.Eth.Blocks.EthGetBlockTransactionCountByNumber _ethGetBlockTransactionCountByNumber;

        public EthGetBlockTransactionCountByNumberUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetBlockTransactionCountByNumber = new RPC.Eth.Blocks.EthGetBlockTransactionCountByNumber(null);
        }

        public IEnumerator SendRequest(BlockParameter block)
        {
            var request = _ethGetBlockTransactionCountByNumber.BuildRequest(block);
            yield return SendRequest(request);
        }
    }


    public class EthGetBlockWithTransactionsHashesByNumberUnityRequest : UnityRpcClient<BlockWithTransactionHashes>
    {
        private readonly RPC.Eth.Blocks.EthGetBlockWithTransactionsHashesByNumber _ethGetBlockWithTransactionsHashesByNumber;

        public EthGetBlockWithTransactionsHashesByNumberUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethGetBlockWithTransactionsHashesByNumber = new RPC.Eth.Blocks.EthGetBlockWithTransactionsHashesByNumber(null);
        }

        public IEnumerator SendRequest(HexBigInteger number)
        {
            var request = _ethGetBlockWithTransactionsHashesByNumber.BuildRequest(number);
            yield return SendRequest(request);
        }

        public IEnumerator SendRequest(BlockParameter blockParameter)
        {
            var request = _ethGetBlockWithTransactionsHashesByNumber.BuildRequest(blockParameter);
            yield return SendRequest(request);
        }
    }


    public class EthFeeHistoryUnityRequest : UnityRpcClient<FeeHistoryResult>
    {
        private readonly RPC.Eth.Transactions.EthFeeHistory _ethFeeHistory;

        public EthFeeHistoryUnityRequest(string url, JsonSerializerSettings jsonSerializerSettings = null) : base(url, jsonSerializerSettings)
        {
            _ethFeeHistory = new RPC.Eth.Transactions.EthFeeHistory(null);
        }

        public IEnumerator SendRequest(HexBigInteger blockCount, BlockParameter highestBlockNumber, double[] rewardPercentiles = null)
        {
            var request = _ethFeeHistory.BuildRequest(blockCount, highestBlockNumber, rewardPercentiles);
            yield return SendRequest(request);
        }
    }
}
